package com.awfulValentine;

import libs.WebDriverUtils.DriverBase;
import libs.WebDriverUtils.SeleniumKeywords;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.testng.Assert;

public class DuplicationPost {
    private SeleniumKeywords seleniumKeywords;

    public DuplicationPost(SeleniumKeywords seleniumKeywords) {
        this.seleniumKeywords = seleniumKeywords;
    }

    public void verifyDuplicate(WebDriver driver) {
        try {
            String error = driver.findElement(By.id("error-page")).getText();
            Assert.assertEquals("Duplicate comment detected; it looks as though you’ve already said that!", error);
            DriverBase.log.info("PASSED - The system was able to detect duplicated post!");
        } catch (Exception ex) {
            DriverBase.log.fail("FAILED - There's no duplicated message from the system!");
            ex.printStackTrace();
        }

    }

  /*  public static void main(String[] args){
        ProductReview productReview = new ProductReview(new SeleniumKeywords());
        WebDriver driver = productReview.getDriver();

        *//*String productXpath = "//div[@id='special-items']//a[contains(@href,'our-love-is-special') and @class='more-info']";
        String nameText = "wb";
        String commentText = "####This is a test comment generated by Selenium" + nameText;
        String emailText = "w@selenium.com";
        String websiteUrl = "www.selenium.com";*//*

        productReview.postComment(driver);

        DuplicationPost duplicationPost = new DuplicationPost();
        duplicationPost.verifyDuplicate(driver);
        driver.quit();
    }*/
}
